name: Build Unsigned Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 4. Construir los archivos web
      - name: Build Web Assets
        run: npm run build

      # 5. Sincronizar Capacitor con Android
      - name: Sync Capacitor
        run: npx cap sync android

      # 6. Construir el APK sin firmar
      - name: Build Unsigned APK
        run: |
          cd android
          ./gradlew assembleDebug

      # 7. Subir el APK como artefacto
      - name: Upload Unsigned APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-unsigned.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
